# Generated by Django 5.2.17 on 2026-09-07 18:39

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tg_user_id', models.BigIntegerField(unique=True)),
                ('display_name', models.CharField(max_length=150)),
            ],
        ),
        migrations.CreateModel(
            name='Template',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('interval_days', models.PositiveIntegerField()),
                ('effort', models.PositiveSmallIntegerField(default=1)),
                ('active', models.BooleanField(default=True)),
                ('last_spawned_at', models.DateTimeField(blank=True, null=True)),
                ('next_due_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('effort', models.PositiveSmallIntegerField(default=1)),
                ('source', models.CharField(choices=[('manual', 'Manual'), ('template', 'Template')], default='manual', max_length=16)),
                ('state', models.CharField(choices=[('open', 'Open'), ('done', 'Done'), ('skipped', 'Skipped')], default='open', max_length=16)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('due_at', models.DateTimeField(blank=True, null=True)),
                ('done_at', models.DateTimeField(blank=True, null=True)),
                ('reminder_level', models.PositiveSmallIntegerField(default=0)),
                ('next_reminder_at', models.DateTimeField(blank=True, null=True)),
                ('assignee', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tasks', to='chores.person')),
                ('template', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tasks', to='chores.template')),
            ],
        ),
        migrations.CreateModel(
            name='CompletionLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('effort', models.PositiveSmallIntegerField(default=1)),
                ('completed_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='completions', to='chores.person')),
                ('task', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='completions', to='chores.task')),
            ],
        ),
    ]
